dist: xenial
language: php
env:
    - ANALYZE=true
matrix:
    include:
        -
            php: '5.4'
            dist: trusty
            env:
                - ANALYZE=false
        -
            php: '5.5'
            dist: trusty
            env:
                - ANALYZE=false
        -
            php: '5.6'
            env:
                - ANALYZE=false
        -
            php: '7.0'
            env:
                - ANALYZE=false
        -
            php: '7.1'
        -
            php: '7.2'
        -
            php: '7.3'
        -
            php: '7.4'
    # https://github.com/travis-ci/travis-ci/issues/6339
    # https://github.com/travis-ci/travis-ci/issues/8912
    allow_failures:
        -
            php: '5.4'
            env:
                - ANALYZE=false
        -
            php: '5.5'
            env:
                - ANALYZE=false
before_script:
    - export COMPOSER_MEMORY_LIMIT=-1
    - composer self-update
    - composer update
script:
    - vendor/bin/phpunit --version
    - vendor/bin/phpunit tests
    - vendor/bin/php-cs-fixer --version
    - vendor/bin/php-cs-fixer fix --dry-run --verbose
    - if [ "$ANALYZE" = "true" ]; then composer global require phpstan/phpstan; fi;
    - if [ "$ANALYZE" = "true" ]; then export PATH=~/.config/composer/vendor/bin:$PATH; fi;
    - if [ "$ANALYZE" = "true" ]; then phpstan --version; fi;
    - if [ "$ANALYZE" = "true" ]; then phpstan analyze sources --level=5; fi;
    - if [ "$ANALYZE" = "true" ]; then phpstan analyze tests --level=1; fi;
after_success:
    - travis_retry vendor/bin/coveralls
