language: php

sudo: false

matrix:
    include:
        -
            php: '5.5'
            env:
                - ANALYZE=false
        -
            php: '5.6'
            env:
                - ANALYZE=false
        -
            php: '7.0'
            env:
                - ANALYZE=false
        -
            php: '7.1'
            env:
                - ANALYZE=true
        -
            php: '7.2'
            env:
                - ANALYZE=true

before_script:
    - composer update

script:
    - vendor/bin/phpunit
    - vendor/bin/php-cs-fixer fix --dry-run --verbose
    - if [ "$ANALYZE" = "true" ]; then composer require phpstan/phpstan-shim; fi;
    - if [ "$ANALYZE" = "true" ]; then php vendor/bin/phpstan analyze sources --configuration=phpstan-sources.neon --level=5; fi;
    - if [ "$ANALYZE" = "true" ]; then php vendor/bin/phpstan analyze tests --configuration=phpstan-tests.neon --level=1; fi;

after_success:
    - travis_retry vendor/bin/coveralls
