language: php
matrix:
    include:
        -
            php: 'hhvm'
            env:
                - ANALYZE=false
        -
            php: '5.5'
            env:
                - ANALYZE=false
        -
            php: '5.6'
            env:
                - ANALYZE=false
        -
            php: '7.0'
            env:
                - ANALYZE=true
        -
            php: '7.1'
            env:
                - ANALYZE=true
    allow_failures:
        # https://github.com/travis-ci/travis-ci/issues/6339
        -
            php: '5.4'
            env:
                - ANALYZE=false
        # https://github.com/guzzle/guzzle/issues/1750
        -
            php: 'nightly'
            env:
                - ANALYZE=true
before_script:
    - composer update
script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs
    - if [ "$ANALYZE" = "true" ]; then composer global require phpstan/phpstan; fi;
    - if [ "$ANALYZE" = "true" ]; then export PATH=~/.composer/vendor/bin:$PATH; fi;
    - if [ "$ANALYZE" = "true" ]; then phpstan analyze sources --configuration=phpstan-sources.neon --level=5; fi;
    - if [ "$ANALYZE" = "true" ]; then phpstan analyze tests --configuration=phpstan-tests.neon --level=1; fi;
after_success:
    - travis_retry vendor/bin/coveralls
